// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QANbuy.Entity
{
    public partial class Comments
    {
        [Key]
        public int ID { get; set; }
        public int UserID { get; set; }
        public int GoodID { get; set; }
        [Required]
        [StringLength(1000)]
        public string Comment { get; set; }
        [Column(TypeName = "date")]
        public DateTime CommentDate { get; set; }
    }
}