// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QANbuy.Entity
{
    [Keyless]
    public partial class GoodView
    {
        public int ID { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        public double Price { get; set; }
        public byte[] GoodPic { get; set; }
        [Required]
        [StringLength(30)]
        public string state { get; set; }
        [Required]
        [StringLength(30)]
        public string type { get; set; }
        [Unicode(false)]
        public string Description { get; set; }
        public double Postage { get; set; }
        [Required]
        [StringLength(30)]
        public string ShipAddress { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreateDate { get; set; }
        public int saleNum { get; set; }
        public int Inventory { get; set; }
        public int TypeId { get; set; }
        public int StateId { get; set; }
    }
}