// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QANbuy.Entity
{
    public partial class Order
    {
        [Key]
        public int ID { get; set; }
        public int GoodID { get; set; }
        [Required]
        [StringLength(30)]
        public string GoodName { get; set; }
        public double GoodPrice { get; set; }
        public byte[] GoodPic { get; set; }
        public double Postage { get; set; }
        public int Num { get; set; }
        public int UserID { get; set; }
        public int State { get; set; }
        public double Payment { get; set; }
        [Required]
        [StringLength(30)]
        public string ShipAddress { get; set; }
        [Required]
        [StringLength(30)]
        public string HarvestAddress { get; set; }
        [Column(TypeName = "date")]
        public DateTime PayDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SendDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HarvestDate { get; set; }
    }
}