// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace QANbuy.Entity
{
    public partial class Qanbuy_DBContext : DbContext
    {
        public Qanbuy_DBContext()
        {
        }

        public Qanbuy_DBContext(DbContextOptions<Qanbuy_DBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<CommentView> CommentView { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<GoodStatus> GoodStatus { get; set; }
        public virtual DbSet<GoodType> GoodType { get; set; }
        public virtual DbSet<GoodView> GoodView { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<OrderView> OrderView { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }
        public virtual DbSet<ShoppingCartView> ShoppingCartView { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=139.224.221.148;Initial Catalog=QANbuy_DB;Persist Security Info=True;User ID=QANstar;Password=Fa473184520403");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CommentView>(entity =>
            {
                entity.ToView("CommentView");
            });

            modelBuilder.Entity<GoodView>(entity =>
            {
                entity.ToView("GoodView");
            });

            modelBuilder.Entity<OrderView>(entity =>
            {
                entity.ToView("OrderView");
            });

            modelBuilder.Entity<ShoppingCart>(entity =>
            {
                entity.HasKey(e => new { e.UserID, e.GoodID });
            });

            modelBuilder.Entity<ShoppingCartView>(entity =>
            {
                entity.ToView("ShoppingCartView");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}