// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QANbuy.Entity
{
    [Keyless]
    public partial class ShoppingCartView
    {
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        public double Price { get; set; }
        public int Num { get; set; }
        public int UserID { get; set; }
        public int GoodID { get; set; }
        public byte[] GoodPic { get; set; }
        public double Postage { get; set; }
    }
}